### ISSUE TITLE
_txRandom is set in init() never changes

### ISSUE THREAD

**Issue by jerryneedell** [brentru/Adafruit_CircuitPython_TinyLoRa#2]
self._txRandom is set in  _init but it is never updated so the same frequency will be used for all transmissions.

**Comment by brentru** [comment]
note to self: patch this by adding a call to update txrandom before the freq.s are selected:
https://github.com/brentru/Adafruit_CircuitPython_TinyLoRa/blob/master/adafruit_tinylora/adafruit_tinylora.py#L239

**Comment by brentru** [comment]
Fixed in lastest `master`. Closing...
