### ISSUE TITLE
release or mpy??

### ISSUE THREAD

**Issue by sabas1080** [brentru/Adafruit_CircuitPython_TinyLoRa#3]
Hi

Any release or mpy ??

Thanks

**Comment by brentru** [comment]
I have some cleanup and documentation to do and then I’ll release :)

**Comment by brentru** [comment]
fyi - probably around the end of this week, i'll do a full merge into the adafruit/ organization repo, then a code review followed by refactoring and a release. Then a guide.

**Comment by sabas1080** [comment]
thanks!
