### ISSUE TITLE
MIC generation does not work on Raspberry Pi

### ISSUE THREAD

**Issue by jerryneedell** [brentru/Adafruit_CircuitPython_TinyLoRa#4]
Just for fun, I tried running this on a Raspberry Pi and ran into some issues,
The MIC generation fails due to this issue https://github.com/adafruit/circuitpython/issues/1361

CircuitPython handles bytes differently than on Linux. In this case it is more C-like and works as expected on CircuitPython, but not on the Pi.
There may well be other issues here as well...
I'm looking into workarounds but just wanted to let you know.

here is the error on the Pi
```
pi@gjnpi3p-1:~/projects/blinka/tinylora $ python3.6 tinylora_simpletest.py
SPI(): __init()
spiPorts: ((0, 11, 10, 9), (1, 21, 20, 19))
for:
0 11 10 9
Line 91
<class 'adafruit_blinka.microcontroller.generic_linux.spi.SPI'>
<adafruit_blinka.microcontroller.generic_linux.spi.SPI object at 0x76a4f7f0>
Traceback (most recent call last):
  File "tinylora_simpletest.py", line 30, in <module>
    lora.send_data(data,len(data),frame_counter)
  File "/home/pi/projects/blinka/tinylora/adafruit_tinylora.py", line 205, in send_data
    mic = aes.calculate_mic(lora_pkt, lora_pkt_len, mic)
  File "/home/pi/projects/blinka/tinylora/adafruit_tinylora_encryption.py", line 281, in calculate_mic
    self._mic_generate_keys(key_k1, key_k2)
  File "/home/pi/projects/blinka/tinylora/adafruit_tinylora_encryption.py", line 348, in _mic_generate_keys
    self._shift_left(key_1)
  File "/home/pi/projects/blinka/tinylora/adafruit_tinylora_encryption.py", line 377, in _shift_left
    data[i] = (data[i] << 1) + overflow
```

**Comment by brentru** [comment]
Tested it on CP and Pi, looks good. Thanks for catching...pushing fix to master and closing

**Comment by jerryneedell** [comment]
you are missing brackets  -- did it work this way -- all the way to the device?
```
diff adafruit_tinylora/adafruit_tinylora_encryption.py ~/projects/TinyLoRa_CircuitPython/adafruit_tinylora/
377c377
<             data[i] = (data[i] << 1) + overflow&0xff
---
>             data[i] = ((data[i] << 1) + overflow)&0xff
```

**Comment by jerryneedell** [comment]
wow -- I guess it works as written -- but it sure looks confusing ...  I was sure the order of operations would not work as you did it.

**Comment by brentru** [comment]
I'll add brackets, it did work..strange.

**Comment by jerryneedell** [comment]
it worked for me too, but it should not!!  "&" is higher precedence than "+"  https://docs.python.org/3/reference/expressions.html#operator-precedence

**Comment by jerryneedell** [comment]
argh -- I read it wrong -- the table is low to high -- so & is lower than "+"   I still think the brackets make it clearer

**Comment by jerryneedell** [comment]
Thanks -- it is the opposite in C  --- very confusing
